export const TOGGLE_CART = "TOGGLE_CART";
export const DELETE_CART = "DELETE_CART";
export const MINUS_CART_COUNT = "MINUS_CART_COUNT";
export const PLUS_CART_COUNT = "PLUS_CART_COUNT";

export const TOGGLE_CHECK_ALL = "TOGGLE_CHECK_ALL";
export const TOGGLE_CHECK = "TOGGLE_CHECK";
